#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE ${DB_NAME};
    \c ${DB_NAME}
    CREATE SCHEMA ${DB_SCHEMA};
    GRANT ALL PRIVILEGES ON DATABASE "${DB_NAME}" TO "${POSTGRES_USER}";

    CREATE DATABASE ${DB_NAME}_test;
    \c ${DB_NAME}_test
    CREATE SCHEMA ${DB_SCHEMA};
    GRANT ALL PRIVILEGES ON DATABASE "${DB_NAME}_test" TO "${POSTGRES_USER}";
EOSQL
